// Code generated by "genum -pkg int -type int -output int hello.csv"; DO NOT EDIT.

package int

// Enum is an enum.
type Enum int

// List of known Enum enums.
const (
	Hello Enum = iota
	Bonjour
	Hallo
	Hola
	Ciao
	Ossu
	Yasou
)
