// Code generated by "genum -pkg one_column_only -type int -validator -stringer hello.csv"; DO NOT EDIT.

package one_column_only

import (
	"fmt"
)

// Enum is an enum.
type Enum int

// List of known Enum enums.
const (
	Hello Enum = iota
	Bonjour
	Hallo
	Hola
	Ciao
	Ossu
	Yasou
)

const _EnumNames = "hellobonjourhalloholaciaoOssuyasou"

var _EnumIndexes = [...]uint8{0, 5, 12, 17, 21, 25, 29, 34}

func lookupEnum(e Enum) (s string, ok bool) {
	e -= 1
	if e < 0 || e >= Enum(len(_EnumIndexes)-1) {
		return "", false
	}
	return _EnumNames[_EnumIndexes[e]:_EnumIndexes[e+1]], true
}

// String implements the fmt.Stringer interface.
func (e Enum) String() string {
	s, ok := lookupEnum(e)
	if !ok {
		return fmt.Sprintf("%[3]s(%[2]d)", "", int(e), "Enum")
	}
	return s
}

// IsValid returns true if the Enum is a known constant.
func (e Enum) IsValid() bool {
	_, ok := lookupEnum(e)
	return ok
}
