// Code generated by "genum -pkg float64 -type float64 -output float64 hello.csv"; DO NOT EDIT.

package float64

// Enum is an enum.
type Enum float64

// List of known Enum enums.
const (
	Hello   Enum = 0
	Bonjour Enum = 0
	Hallo   Enum = 0
	Hola    Enum = 0
	Ciao    Enum = 0
	Ossu    Enum = 0
	Yasou   Enum = 0
)
