// Code generated by "genum -pkg int16 -type int16 -output int16 hello.csv"; DO NOT EDIT.

package int16

// Enum is an enum.
type Enum int16

// List of known Enum enums.
const (
	Hello Enum = iota
	Bonjour
	Hallo
	Hola
	Ciao
	Ossu
	Yasou
)
