linters:
  enable-all: true
  disable:
    - wsl
    - godox
    - gomnd
    - exhaustive
    - exhaustivestruct
    - nlreturn
    - nakedret
    - paralleltest
    - wrapcheck

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - gochecknoglobals
        - funlen
        - dupl
        - gosec
        - maligned

    - path: pkg/genum/helpers\.go
      linters:
        - nestif
    - path: main\.go
      linters:
        - funlen