// Code generated by "genum -pkg uint8 -type uint8 -output uint8 hello.csv"; DO NOT EDIT.

package uint8

// Enum is an enum.
type Enum uint8

// List of known Enum enums.
const (
	Hello Enum = iota
	Bonjour
	Hallo
	Hola
	Ciao
	Ossu
	Yasou
)
