// Code generated by "genum -pkg uint64 -type uint64 -output uint64 hello.csv"; DO NOT EDIT.

package uint64

// Enum is an enum.
type Enum uint64

// List of known Enum enums.
const (
	Hello Enum = iota
	Bonjour
	Hallo
	Hola
	Ciao
	Ossu
	Yasou
)
