// Code generated by "genum -pkg bitmask_uint8 -name Config -bitmask config.csv"; DO NOT EDIT.

package bitmask_uint8

// Config is an enum.
type Config uint8

// List of known Config enums.
const (
	Verbose Config = 1 << iota
	ConfigFromDisk
	DatabaseRequired
	LoggerActivated
	Debug
	FloatSupport
	RecoveryMode
	RebootOnFailure
)

// Has returns in success if this Config is set on it.
func (e Config) Has(e2 Config) bool {
	return e&e2 != 0
}

// Set sets this Config on the current Config.
func (e *Config) Set(e2 Config) {
	*e |= e2
}

// Switch only changes the Config value if necessary.
// It returns true if the requested action has been done.
func (e *Config) Switch(e2 Config, on bool) (done bool) {
	if e.Has(e2) == on {
		return false
	}
	if on {
		e.Set(e2)
	} else {
		e.Unset(e2)
	}
	return true
}

// Toggle toggles this Config value.
func (e *Config) Toggle(e2 Config) {
	*e ^= e2
}

// Unset clears this Config value on the current one.
func (e *Config) Unset(e2 Config) {
	*e &^= e2
}
