// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package genum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Int-0]
	_ = x[Int8-1]
	_ = x[Int16-2]
	_ = x[Int32-3]
	_ = x[Int64-4]
	_ = x[Uint-5]
	_ = x[Uint8-6]
	_ = x[Uint16-7]
	_ = x[Uint32-8]
	_ = x[Uint64-9]
	_ = x[Float32-10]
	_ = x[Float64-11]
	_ = x[String-12]
}

const _Kind_name = "IntInt8Int16Int32Int64UintUint8Uint16Uint32Uint64Float32Float64String"

var _Kind_index = [...]uint8{0, 3, 7, 12, 17, 22, 26, 31, 37, 43, 49, 56, 63, 69}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
