// Code generated by "genum -pkg string -type string -output string hello.csv"; DO NOT EDIT.

package string

// Enum is an enum.
type Enum string

// List of known Enum enums.
const (
	Hello   Enum = "hello"
	Bonjour Enum = "bonjour"
	Hallo   Enum = "hallo"
	Hola    Enum = "hola"
	Ciao    Enum = "ciao"
	Ossu    Enum = "Ossu"
	Yasou   Enum = "yasou"
)
