// Code generated by "genum -pkg int32 -type int32 -output int32 hello.csv"; DO NOT EDIT.

package int32

// Enum is an enum.
type Enum int32

// List of known Enum enums.
const (
	Hello Enum = iota
	Bonjour
	Hallo
	Hola
	Ciao
	Ossu
	Yasou
)
