// Code generated by "genum -pkg uint -type uint -output uint hello.csv"; DO NOT EDIT.

package uint

// Enum is an enum.
type Enum uint

// List of known Enum enums.
const (
	Hello Enum = iota
	Bonjour
	Hallo
	Hola
	Ciao
	Ossu
	Yasou
)
