// Code generated by "genum -pkg int8 -type int8 -output int8 hello.csv"; DO NOT EDIT.

package int8

// Enum is an enum.
type Enum int8

// List of known Enum enums.
const (
	Hello Enum = iota
	Bonjour
	Hallo
	Hola
	Ciao
	Ossu
	Yasou
)
