// Code generated by "genum -pkg uint32 -type uint32 -output uint32 hello.csv"; DO NOT EDIT.

package uint32

// Enum is an enum.
type Enum uint32

// List of known Enum enums.
const (
	Hello Enum = iota
	Bonjour
	Hallo
	Hola
	Ciao
	Ossu
	Yasou
)
