// Code generated by "genum -pkg float32 -type float32 -output float32 hello.csv"; DO NOT EDIT.

package float32

// Enum is an enum.
type Enum float32

// List of known Enum enums.
const (
	Hello   Enum = 0
	Bonjour Enum = 0
	Hallo   Enum = 0
	Hola    Enum = 0
	Ciao    Enum = 0
	Ossu    Enum = 0
	Yasou   Enum = 0
)
