// Code generated by "genum -pkg int64 -type int64 -output int64 hello.csv"; DO NOT EDIT.

package int64

// Enum is an enum.
type Enum int64

// List of known Enum enums.
const (
	Hello Enum = iota
	Bonjour
	Hallo
	Hola
	Ciao
	Ossu
	Yasou
)
