// Code generated by "genum -pkg uint16 -type uint16 -output uint16 hello.csv"; DO NOT EDIT.

package uint16

// Enum is an enum.
type Enum uint16

// List of known Enum enums.
const (
	Hello Enum = iota
	Bonjour
	Hallo
	Hola
	Ciao
	Ossu
	Yasou
)
